Fix for #32
laminas/laminas-developer-tools pull request #33
Opened 2020-10-05 17:22 UTC by Gounlaf

Fix for #32

2020-10-05 18:06 UTC, boesing requested changes
Hey @Gounlaf, thanks for contributing!
Please read all requested changes carefully.

They contain the following suggestions:
- If there are annotations within objects/interfaces which considered to be invalid, please revert them from this PR and move then to a dedicated bugfix PR to fix all invalid annotations
- Any method signature change should be reverted as they are not required to be available for PHP 8.0 and most of the time introduce BC break unless the class or method is considered to be final or private

Had to create 126 comments (most are related to the native PHP typehint extension), so please consider this solution:
- Create a fresh PR with just the PHP 8.0 related changes, please do not use this branch as a starting point unless you revert (or reset) all changes
- Create a fresh PR for all those bugfixes (fixing of invalid annotations)
- Create a fresh PR for all native typehints, we probably can take that branch for the next major version

2020-10-05 18:06 UTC, boesing commented on src/Collector/AutoHideInterface.php
> +    public function canHide(): bool;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/CollectorInterface.php
> +    public function getName(): string;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/CollectorInterface.php
> +    public function getPriority(): int;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ConfigCollector.php
> +    public function getName(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ConfigCollector.php
> +    public function getPriority(): int
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ConfigCollector.php
> +    public function getConfig(): ?array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ConfigCollector.php
> +    public function getApplicationConfig(): ?array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ConfigCollector.php
> +    private function makeArraySerializable(iterable $data): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ConfigCollector.php
> +    private function unserializeArray(array $data): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/DbCollector.php
> +    public function getName(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/DbCollector.php
> +    public function getPriority(): int
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/DbCollector.php
> +    public function canHide(): bool
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/DbCollector.php
> +    public function hasProfiler(): bool
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/DbCollector.php
> +    public function getProfiler(): Profiler
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/DbCollector.php
> +    public function setProfiler(Profiler $profiler): self
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/DbCollector.php
> +    public function getQueryCount(?int $mode = null): self
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/DbCollector.php
> +    public function getQueryTime(?int $mode = null)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/EventCollectorInterface.php
> +    public function collectEvent(string $id, EventInterface $event);
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ExceptionCollector.php
> +    public function getName(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ExceptionCollector.php
> +    public function getPriority(): int
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ExceptionCollector.php
> +    public function hasPreviousException(): bool
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ExceptionCollector.php
> +    public function getException(): SerializableException
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ExceptionCollector.php
> +    public function getPreviousException(): SerializableException
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ExceptionCollector.php
> +    public function getMessage(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ExceptionCollector.php
> +    public function getPreviousMessage(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ExceptionCollector.php
> +    public function getFile(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ExceptionCollector.php
> +    public function getPreviousFile(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ExceptionCollector.php
> +    public function getCode(): int
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ExceptionCollector.php
> +    public function getPreviousCode(): int
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ExceptionCollector.php
> +    public function getTrace(): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ExceptionCollector.php
> +    public function getPreviousTrace(): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/MailCollector.php
> +    public function getName(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/MailCollector.php
> +    public function getPriority(): int
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/MailCollector.php
> +    public function canHide(): bool
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/MailCollector.php
> +    public function getMailsSend(): int
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/MemoryCollector.php
> +    public function getName(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/MemoryCollector.php
> +    public function getPriority(): int
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/MemoryCollector.php
> +    public function collectEvent(string $id, EventInterface $event)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/MemoryCollector.php
> +    public function getMemory(): int
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/MemoryCollector.php
> +    public function hasEventMemory(): int
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/MemoryCollector.php
> +    public function getApplicationEventMemory(): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/RequestCollector.php
> +    public function getName(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/RequestCollector.php
> +    public function getPriority(): int
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/RequestCollector.php
> +    protected function addChildrenToView(ModelInterface $viewModel, callable $addToViewFromModel)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/RequestCollector.php
> +    public function getStatusCode(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/RequestCollector.php
> +    public function getMethod(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/RequestCollector.php
> +    public function getRouteName(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/RequestCollector.php
> +    public function getActionName(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/RequestCollector.php
> +    public function getControllerName(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/RequestCollector.php
> +    public function getOtherParameters(): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/RequestCollector.php
> +    public function getFullControllerName(?bool $short = true): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/RequestCollector.php
> +     * @param bool|null $short
Please only change phpdoc if necessary. I dont see why we have to mark this argument to allow `null`

2020-10-05 18:06 UTC, boesing commented on src/Collector/RequestCollector.php
> +    public function getViews(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/TimeCollector.php
> +    public function getName(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/TimeCollector.php
> +    public function getPriority(): int
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/TimeCollector.php
> +    public function collectEvent(string $id, EventInterface $event)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/TimeCollector.php
> +    public function getStartTime(): float
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/TimeCollector.php
> +    public function getExecutionTime(): float
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/TimeCollector.php
> +    public function hasEventTimes(): bool
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/TimeCollector.php
> +    public function getApplicationEventTimes(): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/TimeCollector.php
> +    private function marshalStartTime(MvcEvent $mvcEvent): float
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/EventLogging/EventContextInterface.php
> +    public function setEvent(EventInterface $event): void;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/EventLogging/EventContextInterface.php
> +    public function getEvent(): EventInterface;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/EventLogging/EventContextProvider.php
> +    public function setEvent(EventInterface $event): void
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/EventLogging/EventContextProvider.php
> +    public function getEvent(): EventInterface
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/EventLogging/EventContextProvider.php
> +    public function getEventTarget(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/EventLogging/EventContextProvider.php
> +    public function getEventTriggerFile(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Exception/SerializableException.php
> +    public function __construct(\Throwable $exception)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Exception/SerializableException.php
> +    public function getFile(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Collector/ExceptionCollector.php
> +    public function hasException(): bool
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Exception/SerializableException.php
> +    public function getTrace(): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Exception/SerializableException.php
> +    public function getTraceAsString(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/View/Helper/Time.php
> +    public function __invoke(int $time, int $precision = 2)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/View/Helper/Memory.php
> +    public function __invoke(int $size, int $precision = 2)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/View/Helper/DetailArray.php
> +    public function __invoke(string $label, array $details, bool $redundant = false)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function getCollectorNames(): array;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function getCollectors(): array;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function getCollector(string $name): ?Collector\CollectorInterface;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function hasCollector(string $name): bool;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function getMethod(): string;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function setMethod(string $method);
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function hasErrors(): bool;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function getErrors(): ?array;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function addError(string $error);
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function getToken(): string;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function setToken(string $token);
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function getTime(): \DateTime;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function setTime(\DateTime $time);
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function getUri(): string;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function getIp(): string;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ReportInterface.php
> +    public function setIp(string $ip);
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function __sleep(): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +        return $this;
Is this necessary or does `addCollector` return void.
If its necessary, please extract this into an own PR as this should considered as a bugfix.

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function getCollectorNames(): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function getCollectors(): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function getCollector($name): ?Collector\CollectorInterface
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function hasCollector(string $name): bool
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function getMethod(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function setMethod(string $method)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function hasErrors(): bool
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function getErrors(): ?array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function addError(string $error)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function getToken(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function setToken(string $token)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function getTime(): \DateTime
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function setTime(\DateTime $time)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function getUri(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function setUri(string $uri)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function getIp(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +    public function setIp(string $ip)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Report.php
> +     * @var \DateTime
Is that legit? If so, please consider creating a different PR with this as a bugfix instead of part of this PR. Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ProfilerEvent.php
> +    public function getReport(): ReportInterface
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ProfilerEvent.php
> +    public function getProfiler(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/ProfilerEvent.php
> +    public function getApplication(): ?ApplicationInterface
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Profiler.php
> +    public function getEventManager(): EventManagerInterface
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Profiler.php
> +    public function getEvent(): ProfilerEvent
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Profiler.php
> +    public function setErrorMode(bool $mode)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Module.php
> +    public function getViewHelperConfig(): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Module.php
> +    public function onLoadModulesPost(EventInterface $event)
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/MatchInterface.php
> +    public function matches(string $pattern);
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/MatchInterface.php
> +    public function getName(): string;
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Listener/ToolbarListener.php
> +    protected function getLatestVersion(string $currentVersion): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Listener/ToolbarListener.php
> +    protected function renderEntries(ProfilerEvent $event): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Exception/SerializableException.php
> +    protected function filterArgs(array $args, int $level = 0): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Exception/SerializableException.php
> +    protected function filterTrace(array $trace, string $file, int $line): array
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:06 UTC, boesing commented on src/Exception/SerializableException.php
> +    public function getMessage(): string
Please do not add native php typehints in this PR as this introduces a BC break. 
Focus on PHP 8.0 compatibility only.
Thanks!

2020-10-05 18:12 UTC, Gounlaf commented
> Had to create 126 comments
Sorry about that 🥺. You shouldn't have make them considering the solution you gave.
So I will split into 3 PR

2020-10-05 18:15 UTC, boesing commented
> Sorry about that 🥺.
No need to sorry for that! These are great additions but we should keep them separated 👍

2020-10-05 18:36 UTC, Gounlaf commented
Reverted changes, squashed force push.

2020-10-05 19:38 UTC, boesing approved these changes
LGTM!

2020-11-01 20:30 UTC, froschdesign requested changes
Looks very good! 👍 

I only suggest two changes:

* The local `phpunit.xsd` can be used in the PHPUnit configuration.
* The dependency to Prophecy can be removed.

Thanks in advance!

2020-11-01 20:30 UTC, froschdesign commented on phpunit.xml.dist
> +         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd"
Please use the XML schema definition from the `vendor` directory of PHPUnit.

2020-11-01 20:30 UTC, froschdesign commented on test/OptionsTest.php
> +
Prophesize is not needed here. Use PHPUnit's function to create a mock.

2020-11-01 20:30 UTC, froschdesign commented on test/OptionsTest.php
>          $reportMock = $this->prophesize(ReportInterface::class)->reveal();
```suggestion
        $reportMock = $this->createMock(ReportInterface::class);
```

2020-11-01 20:30 UTC, froschdesign commented on test/OptionsTest.php
>          $reportMock     = $this->prophesize(ReportInterface::class)->reveal();
```suggestion
        $reportMock     = $this->createMock(ReportInterface::class);
```

2020-11-01 20:30 UTC, froschdesign commented on composer.json
> +        "phpspec/prophecy-phpunit": "^2.0",
Can be removed because PHPUnit's method is good here.

2020-11-01 21:12 UTC, Gounlaf commented
@froschdesign fix sent. Waiting for your OK to squash

2020-11-01 21:15 UTC, froschdesign approved these changes

2020-11-01 21:34 UTC, samsonasik approved these changes

2020-11-02 03:36 UTC, merged